development:
  adapter: postgresql
  encoding: unicode
  database: big_basket
  pool: 5
  username: postgres
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: big_basket
  pool: 5
  username: postgres
  password: root
  host: localhost