# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c32f6dd4f157b1832ac1e868b7f8264c380f8ce45c7fc6662d5b0f5c02a457a0a32354cff37ff413c7b49769da8e5f085afca4cb78163f4390801cb4b7852a00

test:
  secret_key_base: fbabd5a48d665a61e7d100d7be0bff318e66572c02f8fe032d40db8b3d29c06447e01c20ed1238f1bcd6e0abb3149cb431997527672059aaf0b705930be5962a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
